version: 2.1

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-west-2
  
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [ac:2b:8b:9b:de:ce:77:e1:0a:9e:93:06:0b:d6:ff:f6]
      - run:
          name: Install Ansible
          command: |
            apk add --upgrade ansible
      - run:
          name: Run play book
          command: |
            ansible-playbook -i inventory main-remote.yaml 
workflows:
  say-hello-workflow:
    jobs:
      - configure_infrastructure