# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs



jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:13.8.0
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello"

  say-world:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:13.8.0
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - run:
          name: "Say world"
          command: "echo World!!!!"
  write-to-file:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - run:
          name: "Write file"
          command: |
            echo "This is a test file" > output.txt
      - persist_to_workspace:
          root: . 
          paths: 
            - output.txt
  read-from-file:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: "Print file contents"
          command: cat output.txt
      

workflows:
  say-hello-workflow:
    jobs:
      - write-to-file
      - read-from-file:
         requires:
          - write-to-file
